# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-depl
  namespace: default  
spec:  
  replicas: 1  
  selector:
    matchLabels:
      app: nginx-depl 
  template:
    metadata:     
      labels:
        app: nginx-depl
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort : 80

